# Generated by Django 5.0.4 on 2024-04-20 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WakeUpApp', '0003_events_user_alter_events_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
