# Generated by Django 5.0.4 on 2024-04-22 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WakeUpApp', '0004_rename_events_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
